### ISSUE TITLE
Unable to pip install

### ISSUE THREAD

**Issue by gmeans** [tgsmith61591/pyramid#13]
I was unable to do a regular pip install due to the following:

```
▶ pip install pyramid-arima
Collecting pyramid-arima
  Using cached pyramid-arima-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Partial import of pyramid during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/25/vxn94kz91h3gb1m673gj1tqm0000gn/T/pip-build-si3apb7g/pyramid-arima/setup.py", line 41, in <module>
        with open('requirements.txt') as req:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

However installing from github worked fine:

```
▶ pip install --upgrade git+https://github.com/tgsmith61591/pyramid.git    
```

**Comment by tgsmith61591** [comment]
Interesting.. looks like requirements.txt might not be making it into the
.tar dist? I've had success pip installing via wheel and didn't encounter
this. Out of curiosity, what OS are you on? I'll look into making sure the
requirements.txt is making it into the manifest.

**Comment by tgsmith61591** [comment]
Added `requirements.txt` to manifest in 77dc3f7063b7a0fbad8784e36e06823073df239d. Going to let CI tests run, then test installing from the .tar dist before merging into master.

**Comment by gmeans** [comment]
Latest version of OSX (Sierra 10.12.6). I was installing it into an anaconda environment, not sure if that may be part of the issue.

Thanks!

**Comment by tgsmith61591** [comment]
With the latest patch into `master` (see #14), I'm able to download from the source .tar. Reproducible example (with some hyper-verbose output omitted):

```bash
$ conda create -n srctest --yes python=3.5 numpy
$ source activate srctest
(srctest) $ pip install https://pypi.python.org/packages/22/d3/c842154f6054382b544517de6e2bb35b88d2b303edfd6dbee186268196d6/pyramid-arima-0.5.1.tar.gz#md5=fcdfbb4b25f58ad66858333d02685d6c
Collecting https://pypi.python.org/packages/22/d3/c842154f6054382b544517de6e2bb35b88d2b303edfd6dbee186268196d6/pyramid-arima-0.5.1.tar.gz#md5=fcdfbb4b25f58ad66858333d02685d6c
  Using cached pyramid-arima-0.5.1.tar.gz
Requirement already satisfied: numpy>=1.9 in /Users/tgsmith/anaconda3/envs/srctest/lib/python3.5/site-packages (from pyramid-arima==0.5.1)
Collecting scipy>=0.9 (from pyramid-arima==0.5.1)
  Using cached scipy-0.19.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scikit-learn>=0.17 (from pyramid-arima==0.5.1)
  Using cached scikit_learn-0.19.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting statsmodels>=0.8 (from pyramid-arima==0.5.1)
  Using cached statsmodels-0.8.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pandas (from statsmodels>=0.8->pyramid-arima==0.5.1)
  Using cached pandas-0.20.3-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting patsy (from statsmodels>=0.8->pyramid-arima==0.5.1)
  Using cached patsy-0.4.1-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas->statsmodels>=0.8->pyramid-arima==0.5.1)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting python-dateutil>=2 (from pandas->statsmodels>=0.8->pyramid-arima==0.5.1)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting six (from patsy->statsmodels>=0.8->pyramid-arima==0.5.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: pyramid-arima
  Running setup.py bdist_wheel for pyramid-arima ... done
  Stored in directory: /Users/tgsmith/Library/Caches/pip/wheels/fb/d2/34/e227f35e1b0582e80ee74bb1cf6262f69ed1fc3a5b9b59b9eb
Successfully built pyramid-arima
Installing collected packages: scipy, scikit-learn, pytz, six, python-dateutil, pandas, patsy, statsmodels, pyramid-arima
Successfully installed pandas-0.20.3 patsy-0.4.1 pyramid-arima-0.5.1 python-dateutil-2.6.1 pytz-2017.2 scikit-learn-0.19.0 scipy-0.19.1 six-1.10.0 statsmodels-0.8.0
```

This is the tar linked directly from the hotfix release to [pypi](https://pypi.python.org/pypi/pyramid-arima/0.5.1). If you're unable to install from `.whl`, this should now work for you. Let me know if you continue to have trouble!
